apiVersion: v1
kind: Service
metadata:
  name: master-data
  namespace: openapi
  labels:
    app: master-data
    service: master-data
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: master-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: master-data
    service: master-data
  name: master-data
  namespace: openapi
spec:
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0%
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: master-data
  template:
    metadata:
      labels:
        app: master-data
    spec:
      containers:
      - image: asia.gcr.io/poc-innovation-iot/open-api/master-data:1.3
        imagePullPolicy: Always
        name: master-data
        # env:
        # - name: DATABASE_HOST
        #   value: "172.28.240.32"
        envFrom:
        - configMapRef:
            name: common-env
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 256M
          requests:
            cpu: 200m
            memory: 256M
        volumeMounts:
        - mountPath: /app/config
          name: ms-config
      volumes:
      - configMap:
          defaultMode: 420
          name: master-data-config
        name: ms-config