apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: todo-api.me
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: todo-api-ing-svc
            port:
              number: 80